In [2]:
import numpy as np
import pandas as pd

In [26]:
data = pd.read_csv('titanic_MD.csv')

In [4]:
print('Data dataset shape:', data.shape)
data.head()

Data dataset shape: (183, 12)


PassengerId  Survived  Pclass  \
0            2         1       1   
1            4         1       1   
2            7         0       1   
3           11         1       3   
4           12         1       1   

                                                Name     Sex   Age  SibSp  \
0  Cumings, Mrs. John Bradley (Florence Briggs Th...       ?  38.0    1.0   
1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
2                            McCarthy, Mr. Timothy J    male  54.0    0.0   
3                    Sandstrom, Miss. Marguerite Rut  female   NaN    1.0   
4                           Bonnell, Miss. Elizabeth  female  58.0    NaN   

   Parch    Ticket     Fare Cabin Embarked  
0    0.0  PC 17599  71.2833   C85        C  
1    0.0    113803  53.1000  C123        S  
2    0.0     17463  51.8625   E46        S  
3    NaN   PP 9549  16.7000    G6        S  
4    0.0    113783  26.5500  C103        S

In [5]:
np.unique(data['Sex'])  

array(['?', 'female', 'male'], dtype=object)

In [23]:
 # Cambiar los ? por NaN
cols = []
val = []
for col in data.select_dtypes(include='object').columns:
    cols.append(col)
    val.append(data[col].str.contains(r'\?').sum())
pd.DataFrame({
    'cols':cols,
    'val':val
})

cols  val
0      Name    0
1       Sex   51
2    Ticket    0
3     Cabin    0
4  Embarked    0

In [27]:
data.replace(r'\?', np.nan, regex = True, inplace = True)

In [28]:
data.isna().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex            51
Age            25
SibSp           3
Parch          12
Ticket          0
Fare            8
Cabin           0
Embarked       12
dtype: int64

In [18]:
data.head(10)

PassengerId  Survived  Pclass  \
0            2         1       1   
1            4         1       1   
2            7         0       1   
3           11         1       3   
4           12         1       1   
5           22         1       2   
6           24         1       1   
7           28         0       1   
8           53         1       1   
9           55         0       1   

                                                Name     Sex   Age  SibSp  \
0  Cumings, Mrs. John Bradley (Florence Briggs Th...     NaN  38.0    1.0   
1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
2                            McCarthy, Mr. Timothy J    male  54.0    0.0   
3                    Sandstrom, Miss. Marguerite Rut  female   NaN    1.0   
4                           Bonnell, Miss. Elizabeth  female  58.0    NaN   
5                              Beesley, Mr. Lawrence    male  34.0    0.0   
6                       Sloper, Mr. William Thompson     NaN   NaN    0.0   
7                     Fortune, Mr. Charles Alexander     NaN  19.0    3.0   
8           Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.0    1.0   
9                     Ostby, Mr. Engelhart Cornelius    male  65.0    0.0   

   Parch    Ticket      Fare        Cabin Embarked  
0    0.0  PC 17599   71.2833          C85        C  
1    0.0    113803   53.1000         C123        S  
2    0.0     17463   51.8625          E46        S  
3    NaN   PP 9549   16.7000           G6        S  
4    0.0    113783   26.5500         C103        S  
5    0.0    248698   13.0000          D56        S  
6    0.0    113788   35.5000           A6        S  
7    2.0     19950  263.0000  C23 C25 C27        S  
8    NaN  PC 17572   76.7292          D33        C  
9    1.0    113509   61.9792          B30        C

In [19]:
np.unique(data['Age'])  

array([ 0.92,  2.  ,  3.  ,  4.  ,  6.  , 11.  , 14.  , 15.  , 16.  ,
       17.  , 18.  , 19.  , 21.  , 22.  , 23.  , 24.  , 25.  , 27.  ,
       28.  , 29.  , 30.  , 31.  , 32.  , 33.  , 34.  , 35.  , 36.  ,
       36.5 , 37.  , 38.  , 39.  , 40.  , 41.  , 42.  , 43.  , 44.  ,
       45.  , 46.  , 47.  , 48.  , 49.  , 50.  , 51.  , 52.  , 53.  ,
       54.  , 55.  , 56.  , 58.  , 60.  , 61.  , 62.  , 63.  , 64.  ,
       65.  , 70.  , 71.  , 80.  ,   nan])

In [ ]:
# Aproximar los que contengan decimales. 

In [20]:
data['Age'] = round(data['Age'])

In [21]:
np.unique(data['Age'])  

array([ 1.,  2.,  3.,  4.,  6., 11., 14., 15., 16., 17., 18., 19., 21.,
       22., 23., 24., 25., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49., 50., 51., 52., 53., 54., 55., 56., 58., 60., 61., 62., 63.,
       64., 65., 70., 71., 80., nan])

In [23]:
np.unique(data['SibSp'])  

array([ 0.,  1.,  2.,  3., nan])

In [24]:
np.unique(data['Parch'])  

array([ 0.,  1.,  2.,  4., nan])

In [25]:
np.unique(data['Fare'])  
# Tener todo en 2 decimales 

array([  0.    ,   5.    ,   7.65  ,   8.05  ,  10.4625,  10.5   ,
        12.475 ,  12.875 ,  13.    ,  13.7917,  16.7   ,  25.5875,
        25.9292,  26.    ,  26.2833,  26.2875,  26.3875,  26.55  ,
        27.7208,  27.75  ,  28.5   ,  28.7125,  29.7   ,  30.    ,
        30.5   ,  30.6958,  31.    ,  32.3208,  33.5   ,  34.0208,
        34.6542,  35.5   ,  38.5   ,  39.    ,  39.4   ,  39.6   ,
        40.125 ,  49.5   ,  49.5042,  50.4958,  51.4792,  51.8625,
        52.    ,  52.5542,  53.1   ,  55.    ,  55.4417,  55.9   ,
        56.9292,  57.    ,  57.9792,  61.175 ,  61.9792,  63.3583,
        66.6   ,  69.3   ,  71.    ,  71.2833,  75.25  ,  76.7292,
        77.2875,  77.9583,  78.2667,  78.85  ,  79.2   ,  79.65  ,
        81.8583,  83.1583,  83.475 ,  86.5   ,  89.1042,  90.    ,
        91.0792,  93.5   , 106.425 , 108.9   , 110.8833, 113.275 ,
       120.    , 134.5   , 135.6333, 146.5208, 151.55  , 153.4625,
       164.8667, 211.3375, 211.5   , 227.525 , 247.5208, 262.3

In [27]:
data['Fare'] = round(data['Fare'], 2)

In [33]:
data['Embarked'].head(10) 

0    C
1    S
2    S
3    S
4    S
5    S
6    S
7    S
8    C
9    C
Name: Embarked, dtype: object

In [34]:
pct = pd.DataFrame(data.isna().sum()/data.shape[0], columns = ['pct']).reset_index()
pct

index       pct
0   PassengerId  0.000000
1      Survived  0.000000
2        Pclass  0.000000
3          Name  0.000000
4           Sex  0.278689
5           Age  0.136612
6         SibSp  0.016393
7         Parch  0.065574
8        Ticket  0.000000
9          Fare  0.043716
10        Cabin  0.000000
11     Embarked  0.065574

In [38]:
a = 183 * 0.28
b = 183 - a
b, a

(131.76, 51.24)